// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-TGTKQbA8X5T3gKgjWG3bTHPRjjSRDo',
    appId: '1:1045018031814:web:72bbb6e8c00a146098c9c7',
    messagingSenderId: '1045018031814',
    projectId: 'medication-reminder-app-336e5',
    authDomain: 'medication-reminder-app-336e5.firebaseapp.com',
    storageBucket: 'medication-reminder-app-336e5.appspot.com',
    measurementId: 'G-45PV8V2LF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcEQA8vNZzUdfhzs88Iw7fs5sM-WysPAc',
    appId: '1:1045018031814:android:0b826df028bf59c298c9c7',
    messagingSenderId: '1045018031814',
    projectId: 'medication-reminder-app-336e5',
    storageBucket: 'medication-reminder-app-336e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ElPZEw4ODDXgtDbnio138JtGzS-DZ14',
    appId: '1:1045018031814:ios:dee51de122279b6f98c9c7',
    messagingSenderId: '1045018031814',
    projectId: 'medication-reminder-app-336e5',
    storageBucket: 'medication-reminder-app-336e5.appspot.com',
    iosBundleId: 'com.example.mms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ElPZEw4ODDXgtDbnio138JtGzS-DZ14',
    appId: '1:1045018031814:ios:14382981771e13ed98c9c7',
    messagingSenderId: '1045018031814',
    projectId: 'medication-reminder-app-336e5',
    storageBucket: 'medication-reminder-app-336e5.appspot.com',
    iosBundleId: 'com.example.mms.RunnerTests',
  );
}